// App

export const INIT_APP = "INIT_APP";

// Bookshelf

export const FETCH_BOOKS_START = "FETCH_BOOKS_START";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";

export const FETCH_NEXT_PAGE_START = "FETCH_NEXT_PAGE_START";
export const FETCH_NEXT_PAGE_SUCCESS = "FETCH_NEXT_PAGE_SUCCESS";
export const FETCH_NEXT_PAGE_FAILURE = "FETCH_NEXT_PAGE_FAILURE";

export const CLEAR_BOOKS = "CLEAR_BOOKS";

// Book

export const FETCH_BOOK_BY_ID_START = "FETCH_BOOK_BY_ID_START";
export const FETCH_BOOK_BY_ID_SUCCESS = "FETCH_BOOK_BY_ID_SUCCESS";
export const FETCH_BOOK_BY_ID_FAILURE = "FETCH_BOOK_BY_ID_FAILURE";
